### ISSUE TITLE
2.0.2-rc9, label "exclusion/inclusion" is not changed after device exclusion/inclusion

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#141]
label "exclusion/inclusion" is not changed after device exclusion/inclusion

**Comment by PoltoS** [comment]
@vades is it from today's change?

**Comment by vades** [comment]
Works OK
![141_exclusion](https://cloud.githubusercontent.com/assets/1451741/10509871/0bf35b7a-7330-11e5-8a32-08149aff09dd.png)
![141_ready_include](https://cloud.githubusercontent.com/assets/1451741/10509874/0f477806-7330-11e5-8b9c-8579af13fdd6.png)
![141_included](https://cloud.githubusercontent.com/assets/1451741/10509880/1866b398-7330-11e5-91c0-74abb16a7181.png)

**Comment by PoltoS** [comment]
Means you can not reproduce it? This harms me every day, please try again!

**Comment by pz1** [comment]
FWIW: I can confirm for v2.1.1 that the screen is **not** automatically updated after inclusion

**Comment by vades** [comment]
Yes I can't reproduce it?

**Comment by PoltoS** [comment]
oh! found it!

You are use in next request of /ZWaveAPI/Data/<timestamp> your local time insted of time from last response (as it should be).

Here is the proof:
![bug](https://cloud.githubusercontent.com/assets/3664383/10511739/14abd9c2-7344-11e5-99a3-27661d9b8a50.png)

You don't see it since your clock on Pi is same as on your machine. We see it because TimeZone is different for my box (or there is a small lag in time).

Please fix it and check SmartHome UI for same problem.

**Comment by PoltoS** [comment]
Again, next  request URI should contain timestamp of last "updateTime" to get everything changed since last update time.
